/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_ianbeltrand;

import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author kevin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        DefaultComboBoxModel model = (DefaultComboBoxModel)TipoComboBox.getModel();
        model.addElement("Artista");
        model.addElement("Cliente");
        TipoComboBox.setModel(model);
        
        DefaultComboBoxModel model2 = (DefaultComboBoxModel)TipoLanzamientoComboBox.getModel();
        model2.addElement("Album");
        model2.addElement("Single");
        TipoLanzamientoComboBox.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SIGNING_IN = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        UsernameS = new javax.swing.JTextField();
        PasswordS = new javax.swing.JTextField();
        AgeS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        TipoComboBox = new javax.swing.JComboBox<>();
        Artista = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TituloLanzamientoC = new javax.swing.JTextField();
        TipoLanzamientoComboBox = new javax.swing.JComboBox<>();
        PublicarButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlbumSinglesTree = new javax.swing.JTree();
        CrearCancion = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DuracionCC = new javax.swing.JTextField();
        TituloCC = new javax.swing.JTextField();
        AñadirCC = new javax.swing.JButton();
        Cliente = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaCanciones = new javax.swing.JList<>();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jToolBar5 = new javax.swing.JToolBar();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree3 = new javax.swing.JTree();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jToolBar6 = new javax.swing.JToolBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        AgregadasList = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CancionesAgregar = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        CRUDBibliotecaArtista = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        PopUpTree = new javax.swing.JPopupMenu();
        AgregarCancion = new javax.swing.JMenuItem();
        EliminarAlbum = new javax.swing.JMenuItem();
        PopUpSingles = new javax.swing.JPopupMenu();
        EliminarSingles = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameL = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        SigninButton = new javax.swing.JButton();
        PasswordL = new javax.swing.JPasswordField();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("SIGN IN");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel7.setText("Age");

        SignInButton.setText("SIGN IN");
        SignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SIGNING_INLayout = new javax.swing.GroupLayout(SIGNING_IN.getContentPane());
        SIGNING_IN.getContentPane().setLayout(SIGNING_INLayout);
        SIGNING_INLayout.setHorizontalGroup(
            SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIGNING_INLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameS)
                    .addComponent(PasswordS)
                    .addComponent(AgeS, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIGNING_INLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIGNING_INLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIGNING_INLayout.createSequentialGroup()
                        .addComponent(SignInButton)
                        .addGap(266, 266, 266))))
        );
        SIGNING_INLayout.setVerticalGroup(
            SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIGNING_INLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(SIGNING_INLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addComponent(SignInButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel8.setText("BEATING BEATS");

        jToolBar1.setRollover(true);

        jLabel9.setText("Titulo del Lanzamiento");

        TipoLanzamientoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoLanzamientoComboBoxActionPerformed(evt);
            }
        });

        PublicarButton.setText("PUBLICAR");
        PublicarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PublicarButtonMouseClicked(evt);
            }
        });

        jLabel10.setText("Tipo de Lanzamiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PublicarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TipoLanzamientoComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(TituloLanzamientoC))
                        .addGap(0, 233, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TituloLanzamientoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(TipoLanzamientoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(PublicarButton)
                .addContainerGap())
        );

        jToolBar1.add(jPanel1);

        jTabbedPane1.addTab("CREAR LANZAMIENTO", jToolBar1);

        jToolBar2.setRollover(true);

        jLabel14.setText("TU BIBLIOTECA DE LANZAMIENTOS");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        AlbumSinglesTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        AlbumSinglesTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlbumSinglesTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AlbumSinglesTree);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 378, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel2);

        jTabbedPane1.addTab("BIBLIOTECA", jToolBar2);

        javax.swing.GroupLayout ArtistaLayout = new javax.swing.GroupLayout(Artista.getContentPane());
        Artista.getContentPane().setLayout(ArtistaLayout);
        ArtistaLayout.setHorizontalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistaLayout.createSequentialGroup()
                .addGroup(ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArtistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(ArtistaLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ArtistaLayout.setVerticalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("AÑADIENDO CANCION");

        jLabel12.setText("TITULO");

        jLabel13.setText("DURACION (min)");

        AñadirCC.setText("AÑADIR");
        AñadirCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirCCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CrearCancionLayout = new javax.swing.GroupLayout(CrearCancion.getContentPane());
        CrearCancion.getContentPane().setLayout(CrearCancionLayout);
        CrearCancionLayout.setHorizontalGroup(
            CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCancionLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(CrearCancionLayout.createSequentialGroup()
                        .addGroup(CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloCC, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(DuracionCC))))
                .addGap(130, 130, 130))
            .addGroup(CrearCancionLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(AñadirCC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearCancionLayout.setVerticalGroup(
            CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCancionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addGap(70, 70, 70)
                .addGroup(CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TituloCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CrearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DuracionCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(AñadirCC)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Onyx", 1, 48)); // NOI18N
        jLabel15.setText("BEATING BEATS");

        jToolBar3.setRollover(true);

        jLabel16.setText("TODAS LAS CANCIONES, TODO EN LA PALMA DE TU MANO");

        ListaCanciones.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ListaCanciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 224, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar3.add(jPanel3);

        jTabbedPane2.addTab("CANCIONES", jToolBar3);

        jToolBar4.setRollover(true);

        jLabel17.setText("TODAS LAS LISTAS DE REPRODUCCION CREADAS POR LOS USUARIOS");

        jScrollPane3.setViewportView(jTree2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 156, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel4);

        jTabbedPane2.addTab("LISTAS DE REPRODUCCION", jToolBar4);

        jToolBar5.setRollover(true);

        jLabel18.setText("LISTAS DE REPRODUCCION CREADAS Y GUARDADAS");

        jScrollPane4.setViewportView(jTree3);

        jLabel23.setText("CANCIONES FAVORITAS");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 155, Short.MAX_VALUE))
                            .addComponent(jScrollPane7)))
                    .addComponent(jLabel18))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );

        jToolBar5.add(jPanel5);

        jTabbedPane2.addTab("BIBLIOTECA", jToolBar5);

        jToolBar6.setRollover(true);

        jLabel19.setText("CREANDO LISTA DE REPRODUCCION");

        jLabel20.setText("Nombre");

        jLabel21.setText("Canciones Añadidas");

        AgregadasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(AgregadasList);

        jLabel22.setText("Canciones");

        CancionesAgregar.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(CancionesAgregar);

        jButton6.setText("AÑADIR");

        jButton7.setText("CREAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton6)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        jToolBar6.add(jPanel6);

        jTabbedPane2.addTab("CREAR", jToolBar6);

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente.getContentPane());
        Cliente.getContentPane().setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel15)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        Eliminar.setText("Eliminar Cancion");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        CRUDBibliotecaArtista.add(Eliminar);

        AgregarCancion.setText("Agregar Cancion");
        AgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCancionActionPerformed(evt);
            }
        });
        PopUpTree.add(AgregarCancion);

        EliminarAlbum.setText("Eliminar Album");
        EliminarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAlbumActionPerformed(evt);
            }
        });
        PopUpTree.add(EliminarAlbum);

        EliminarSingles.setText("EliminarSingles");
        EliminarSingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSinglesActionPerformed(evt);
            }
        });
        PopUpSingles.add(EliminarSingles);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Onyx", 1, 48)); // NOI18N
        jLabel1.setText("BEATING BEATS");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        LoginButton.setText("LOG IN");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        SigninButton.setText("SIGN IN");
        SigninButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(UsernameL))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginButton)
                            .addComponent(PasswordL))))
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SigninButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UsernameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(LoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(SigninButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoLanzamientoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoLanzamientoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoLanzamientoComboBoxActionPerformed

    private void SignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseClicked
        // TODO add your handling code here:
        String username = UsernameS.getText();
        String password = PasswordS.getText();
        int age = Integer.parseInt(AgeS.getText());
        String Tipo = TipoComboBox.getSelectedItem().toString();
        
        if(admi.BuscarUsuario(username) == null){
            if(Tipo.equals("Cliente")){
                if(age >= 12){
                    Cliente cliente = new Cliente(username, password, age, Tipo);
                    admi.usuarios.add(cliente);
                    try {
                        admi.EscribirArchivo(cliente);
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    ActualC = cliente;
                    UsernameS.setText("");
                    PasswordS.setText("");
                    AgeS.setText("");
                    ActualizarListaCanciones();
                    Cliente.setModal(true);
                    Cliente.pack();
                    Cliente.setLocationRelativeTo(this);
                    Cliente.setVisible(true);

                    
                }else{
                    JOptionPane.showMessageDialog(SIGNING_IN, "No tienes la edad necesaria");
                }
            }else{
                if(Tipo.equals("Artista")){
                    if(age >= 18){
                        String nombreArtista = JOptionPane.showInputDialog(SIGNING_IN, "Ingresa tu nombre de artista: ");
                        Artista artista = new Artista(username, password, age, Tipo, nombreArtista);
                        admi.usuarios.add(artista);
                        try {
                            admi.EscribirArchivo(artista);
                        } catch (IOException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        ActualA = (Artista)artista;
                        UsernameS.setText("");
                        PasswordS.setText("");
                        AgeS.setText("");
                        ActualizarTreeArtista();
                        Artista.setModal(true);
                        Artista.pack();
                        Artista.setLocationRelativeTo(this);
                        Artista.setVisible(true);

                        
                    }else{
                        JOptionPane.showMessageDialog(SIGNING_IN, "No tienes la edad necesaria");
                    }
                }
            }
        }
    }//GEN-LAST:event_SignInButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        String username = UsernameL.getText();
        String password = PasswordL.getText();
        
        if(admi.BuscarUsuario(username) != null){
            Usuario usuario = admi.BuscarUsuario(username);
            if(usuario.getUsername().equals(username) && usuario.getPassword().equals(password)){
                if(usuario.Tipo.equals("Artista")){
                    ActualA = (Artista)usuario;
                    UsernameL.setText("");
                    PasswordL.setText("");
                    Artista.setModal(true);
                    Artista.pack();
                    Artista.setLocationRelativeTo(this);
                    Artista.setVisible(true);
                    
                    
                }else{
                    ActualC = (Cliente)usuario;
                    ActualizarListaCanciones();
                    UsernameL.setText("");
                    PasswordL.setText("");
                    Cliente.setModal(true);
                    Cliente.pack();
                    Cliente.setLocationRelativeTo(this);
                    Cliente.setVisible(true);
                    
                }
            }else{
                JOptionPane.showMessageDialog(this, "Password Incorrecta");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se encontraron dichas credenciales");
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void SigninButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninButtonMouseClicked
        // TODO add your handling code here:
        SIGNING_IN.setModal(true);
        SIGNING_IN.pack();
        SIGNING_IN.setLocationRelativeTo(this);
        SIGNING_IN.setVisible(true);
    }//GEN-LAST:event_SigninButtonMouseClicked

    private void PublicarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PublicarButtonMouseClicked
        // TODO add your handling code here:
        if(TipoLanzamientoComboBox.getSelectedItem().toString().equals("Album")){
            int cantidadCanciones = Integer.parseInt(JOptionPane.showInputDialog(Artista, "Cantidad de canciones que contiene el album: "));
            String Titulo = TituloLanzamientoC.getText();
            Date fecha = new Date();
            
            Album album = new Album(Titulo, fecha, cantidadCanciones);
            
            Artista artista = ActualA;
            artista.getAlbumes().add(album);
            ActualizarTreeArtista();
        }else{
            if(TipoLanzamientoComboBox.getSelectedItem().toString().equals("Single")){
                TituloSingle = TituloLanzamientoC.getText();
                
                CrearCancion.setModal(true);
                CrearCancion.pack();
                CrearCancion.setLocationRelativeTo(this);
                CrearCancion.setVisible(true);
                
                
                Single single = new Single(TituloLanzamientoC.getText(), new Date(), cancion);
                
                Artista artista = ActualA;
                artista.getSingles().add(single);
                ActualizarTreeArtista();
            }
        }
    }//GEN-LAST:event_PublicarButtonMouseClicked

    public void ActualizarListaCanciones(){
        DefaultListModel model = (DefaultListModel)ListaCanciones.getModel();
        
        model.clear();
        for (Cancion cancion : admi.canciones){
            model.addElement(cancion);
        }
        
        ListaCanciones.setModel(model);
        CancionesAgregar.setModel(model);
    }
    
    public void ActualizarTreeArtista(){
        DefaultTreeModel model = (DefaultTreeModel)AlbumSinglesTree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        DefaultMutableTreeNode Singles = new DefaultMutableTreeNode("Singles");
        DefaultMutableTreeNode canciones = null;
        
        for (Single single : ActualA.getSingles()){
            canciones = new DefaultMutableTreeNode(single.getSingleCancion());
            Singles.add(canciones);
        }
        
        root.add(Singles);
        
        DefaultMutableTreeNode Albums = new DefaultMutableTreeNode("Albums");
        DefaultMutableTreeNode album = null;
        
        for (Album album1 : ActualA.getAlbumes()){
            album = new DefaultMutableTreeNode(album1);
            for (Cancion cancion : album1.getCanciones()){
                canciones = new DefaultMutableTreeNode(cancion);
                album.add(canciones);
            }
            Albums.add(album);
        }
        
        root.add(Albums);
        model.reload();
    }
    
    private void AñadirCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirCCMouseClicked
        // TODO add your handling code here:
        String title = TituloCC.getText();
        int Duracion = Integer.parseInt(DuracionCC.getText());
        String NombreAlbum = TituloSingle;
        
        Cancion cancionnueva = new Cancion(title, Duracion, NombreAlbum);
        
        cancion = cancionnueva;
        admi.canciones.add(cancionnueva);
        CrearCancion.setVisible(false);
    }//GEN-LAST:event_AñadirCCMouseClicked

    private void AlbumSinglesTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlbumSinglesTreeMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = AlbumSinglesTree.getClosestRowForLocation(evt.getX(), evt.getY());
            AlbumSinglesTree.setSelectionRow(row);
            Object Posicion = AlbumSinglesTree.getSelectionPath().getLastPathComponent();
            SelectedNode = (DefaultMutableTreeNode) Posicion;
            if (SelectedNode.getUserObject() instanceof Cancion){
                cancion = (Cancion) SelectedNode.getUserObject();
                CRUDBibliotecaArtista.show(evt.getComponent(), evt.getX(), evt.getY());
            }

            if (SelectedNode.getUserObject() instanceof Single){
                singleActual = (Single) SelectedNode.getUserObject();
                PopUpSingles.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            
            if (SelectedNode.getUserObject() instanceof Album){
                albumActual = (Album) SelectedNode.getUserObject();
                PopUpTree.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_AlbumSinglesTreeMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        cancion = (Cancion) SelectedNode.getUserObject();
        admi.canciones.remove(cancion);
        DefaultTreeModel model = (DefaultTreeModel)AlbumSinglesTree.getModel();
        model.removeNodeFromParent(SelectedNode);
        model.reload();
    }//GEN-LAST:event_EliminarActionPerformed

    private void EliminarSinglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSinglesActionPerformed
        // TODO add your handling code here:
        singleActual = (Single)SelectedNode.getUserObject();
        ActualA.getSingles().remove(singleActual);
    }//GEN-LAST:event_EliminarSinglesActionPerformed

    private void AgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCancionActionPerformed
        // TODO add your handling code here:
        albumActual = (Album)SelectedNode.getUserObject();
        TituloSingle = albumActual.getTitle();
        
        CrearCancion.setModal(true);
        CrearCancion.pack();
        CrearCancion.setLocationRelativeTo(this);
        CrearCancion.setVisible(true);
        
        albumActual.getCanciones().add(cancion);
        
        ActualizarTreeArtista();
    }//GEN-LAST:event_AgregarCancionActionPerformed

    private void EliminarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAlbumActionPerformed
        // TODO add your handling code here:
        albumActual = (Album)SelectedNode.getUserObject();
        
        DefaultTreeModel model = (DefaultTreeModel)AlbumSinglesTree.getModel();
        model.removeNodeFromParent(SelectedNode);
        model.reload();
        
        ActualA.getAlbumes().remove(albumActual);
    }//GEN-LAST:event_EliminarAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeS;
    private javax.swing.JList<String> AgregadasList;
    private javax.swing.JMenuItem AgregarCancion;
    private javax.swing.JTree AlbumSinglesTree;
    private javax.swing.JDialog Artista;
    private javax.swing.JButton AñadirCC;
    private javax.swing.JPopupMenu CRUDBibliotecaArtista;
    private javax.swing.JList<String> CancionesAgregar;
    private javax.swing.JDialog Cliente;
    private javax.swing.JDialog CrearCancion;
    private javax.swing.JTextField DuracionCC;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem EliminarAlbum;
    private javax.swing.JMenuItem EliminarSingles;
    private javax.swing.JList<String> ListaCanciones;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordL;
    private javax.swing.JTextField PasswordS;
    private javax.swing.JPopupMenu PopUpSingles;
    private javax.swing.JPopupMenu PopUpTree;
    private javax.swing.JButton PublicarButton;
    private javax.swing.JDialog SIGNING_IN;
    private javax.swing.JButton SignInButton;
    private javax.swing.JButton SigninButton;
    private javax.swing.JComboBox<String> TipoComboBox;
    private javax.swing.JComboBox<String> TipoLanzamientoComboBox;
    private javax.swing.JTextField TituloCC;
    private javax.swing.JTextField TituloLanzamientoC;
    private javax.swing.JTextField UsernameL;
    private javax.swing.JTextField UsernameS;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JTree jTree2;
    private javax.swing.JTree jTree3;
    // End of variables declaration//GEN-END:variables
    Admi admi = new Admi();
    Artista ActualA = null;
    Cliente ActualC = null;
    Album albumActual = null;
    Single singleActual = null;
    int CancionesPorCrear = 0;
    Cancion cancion = null;
    DefaultMutableTreeNode SelectedNode = null;
    String TituloSingle = "";
}
